### ISSUE TITLE
List more than 5 items on homepage

### ISSUE THREAD

**Issue by javielico** [kathyqian/crisp#42]
Hi there,

I'm using ghost 1.1.2 with crisp and turns out that on my homepage there's only listed 5 items, can you please specify what is the setting that needs to be changed to list more than 5 items per page?

Thanks,
Javi.

**Comment by javielico** [comment]
Fixed! by using:

"config": {
"posts_per_page": 25
}

on package.json on the root of the theme :)

**Comment by angelcosta** [comment]
Could you paste it here? I tried, but see no change, I even deactivated and reactivated the theme and nothing.
