### ISSUE TITLE
posts_per_page in package.json not working

### ISSUE THREAD

**Issue by jonbesga** [kathyqian/crisp#44]
I am using Ghost 1.19.0.

**Comment by howsonwhocodes** [comment]
I also have this issue. This is my current package.json

{
    "name"        : "Crisp",
    "version"     : "0.5.1",
    "description" : "A minimalist, responsive, and open-source theme for Ghost",
    "author"      : "Kathy Qian",
    "homepage"    : "https://github.com/kathyqian/crisp-ghost-theme"
},
"config": {
        "posts_per_page": 10
    }

Thanks,

Tom.

**Comment by howsonwhocodes** [comment]
Hi,

I was able to fix this by rewriting the package.json for ghost v1. Please see below:

Thanks,

Tom.

{
    "name": "crisp",
    "description": "A minimalist, responsive, and open-source theme for Ghost.",
    "demo": "https://to-fill-in.com",
    "version": "2.1.7",
    "engines": {
        "ghost": ">=1.2.0"
    },
    "license": "MIT",
    "screenshots": {
        "desktop": "assets/list.png",
        "mobile": "assets/single.png"
    },
    "author": {
        "name": "Kathy Qian",
        "email": "hello@someone.com",
        "url": "https://kathyqian.com/"
    },
    "gpm": {
        "type": "theme",
        "categories": [
            "Minimal",
            "fresh"
        ]
    },
    "keywords": [
        "ghost",
        "theme"
    ],
    "repository": {
        "type": "git",
        "url": "https://github.com/kathyqian/crisp/crisp.git"
    },
    "config": {
        "posts_per_page": 10
    }
}

**Comment by talmai** [comment]
I think this issue should be closed. Just tested it, and it is working.

> cat content/themes/crisp/package.json

{
    "name"        : "Crisp",
    "version"     : "0.5.1",
    "description" : "A minimalist, responsive, and open-source theme for Ghost",
    "author"      : "Kathy Qian",
    "config": {
        "posts_per_page": 25
    },
    "homepage"    : "https://github.com/kathyqian/crisp-ghost-theme",
    "license"     : "Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International"
}
